console.log("Hi there! My first Javascript code!")
console.log(document.querySelector(".greeting"))
let greetingDiv = document.querySelector (".greeting")

greetingDiv.textContent = "Welcome to my page! This page was generated by my Javascript code."